// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WOD8QIfhKIJP1o-6BoXWGqbifzFbAgI',
    appId: '1:827167699809:web:69730014aa6ab775c2cb20',
    messagingSenderId: '827167699809',
    projectId: 'tic-tac-toe-b3365',
    authDomain: 'tic-tac-toe-b3365.firebaseapp.com',
    storageBucket: 'tic-tac-toe-b3365.firebasestorage.app',
    measurementId: 'G-9ZGX5XFLBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLtkVH17VE2qxYTZlZ1F1poISnM30AHk',
    appId: '1:827167699809:android:8d625935d0cb528cc2cb20',
    messagingSenderId: '827167699809',
    projectId: 'tic-tac-toe-b3365',
    storageBucket: 'tic-tac-toe-b3365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXfI3c1JensbYd0Q5LoOHRCCKr-P4pmY',
    appId: '1:827167699809:ios:d5449b8191f65bc6c2cb20',
    messagingSenderId: '827167699809',
    projectId: 'tic-tac-toe-b3365',
    storageBucket: 'tic-tac-toe-b3365.firebasestorage.app',
    iosClientId: '827167699809-j6bg3p5qqbodd6f9f31lk0gf8pqod7gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXfI3c1JensbYd0Q5LoOHRCCKr-P4pmY',
    appId: '1:827167699809:ios:d5449b8191f65bc6c2cb20',
    messagingSenderId: '827167699809',
    projectId: 'tic-tac-toe-b3365',
    storageBucket: 'tic-tac-toe-b3365.firebasestorage.app',
    iosClientId: '827167699809-j6bg3p5qqbodd6f9f31lk0gf8pqod7gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0WOD8QIfhKIJP1o-6BoXWGqbifzFbAgI',
    appId: '1:827167699809:web:8e888018f8d247d9c2cb20',
    messagingSenderId: '827167699809',
    projectId: 'tic-tac-toe-b3365',
    authDomain: 'tic-tac-toe-b3365.firebaseapp.com',
    storageBucket: 'tic-tac-toe-b3365.firebasestorage.app',
    measurementId: 'G-JPCEH2ZC1G',
  );
}
